### ISSUE TITLE
Reader Initialization always writes to console

### ISSUE THREAD

**Issue by markphilipp** [stonelasley/barcode-parsing#3]
Could I create a PR to optionally turn off the console output for reader initialization [here](https://github.com/stonelasley/barcode-parsing/blob/master/src/barcode-parser.ts#L53)?  Would there be a preferred method for turning it off?  

Options that I can think of off the top of my head:
- check a node env variable like `NODE_ENV === "development"` or something similar
- Add it as an option for the `IParserConfiguration` 

Thoughts?

**Comment by stonelasley** [comment]
parserconfiguration.verbose flag was added previously to accomplish this. my apologies for years late response.
